# Generated by Django 5.0.2 on 2024-02-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_summarizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
