# Generated by Django 4.1.13 on 2024-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommend",
            name="title",
            field=models.ManyToManyField(
                related_name="titlee", to="news_recommendation.title"
            ),
        ),
    ]
